# Generated by Django 5.1.7 on 2025-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complex_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='default_meal_name', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='simple_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unsaturated_fat',
            field=models.FloatField(default=0),
        ),
    ]
