# Generated by Django 5.1.7 on 2025-04-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_complex_carbs_product_fiber_product_kcal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='default_meal_name', max_length=100, unique=True),
        ),
    ]
