# Generated by Django 5.1.7 on 2025-04-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealproduct',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
    ]
