# Generated by Django 5.1.7 on 2025-04-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_dailyintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='dailyIntake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
