# Generated by Django 5.1.7 on 2025-05-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_userdetails_remove_usermeal_meal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
